### ISSUE TITLE
درخواست راهنمای استفاده در سورس

### ISSUE THREAD

**Issue by hitaspdotnet** [ImanMh/persianRex#10]
سلام
من هیچگونه اطلاعاتی در زمینه جاوا ندارم
به اجبار چند روزی هست که دارم یاد میگیرم. پروژه اصلی من یک چت بات با فرم ورک مایکروسافت هست. تمام ورودی خروجی ها رو به خوبی بین پروژه اصلی که سی شارپ هست با پروژه جاوام ست کردم. اما خروجی کد جاوام یک رشته نا مفهوم میشه که باعث میشه پروژه سی شارپ خطا بده.
من چجوری میتونم از این ماژول شما برای رفع اشکال استفاده کنم؟
نمونه کد:
`const greetings = [
    'how are you',
    'how r u',
    'salam',
    'slm',
    'سلام',
    'چطوری',
    'س',
    [...]
];

module.exports = {
    recognize: function (context, callback) {
        const text = context.message.text
            .replace(/[!?,.\/\\\[\]\{\}\(\)]/g, '')
            .trim()
            .toLowerCase();

        const recognized = {
            entities: [],
            intent: null,
            matched: undefined,
            expression: undefined,
            intents: [],
            score: 0
        }

        if (greetings.some(phrase => text === phrase)) {
            recognized.intent = 'Greeting';
            recognized.score = 1;
        }

        callback.call(null, null, recognized);
    }
};`
توی این کد با کلمات انگلیسی یا فینگلیش بدون مشکل کار میکنه اما وقتی ورودی فارسی میگیره نمیتونه درخواست رو پردازش کنه و یه رشته نامفهوم به کانورتور سی شارپ میفرسته

**Comment by ImanMh** [comment]
شما می تونید از متد hasPersian استفاده کنید.


```
    if (persianRex.hasText.test(stringThatMayContainPersian) {
        //do something
    } else {
       //do something else
    }
```

Anyway it's not an issue with the lib so I close it, If you still have problems you can send me a message on telegram. "09132053044"
