### ISSUE TITLE
مشکل با اعداد

### ISSUE THREAD

**Issue by amirify** [ImanMh/persianRex#12]
سلام، حتی زمانی که کیبورد فارسیه توابع زیر برای اعداد، نادرست برمیگردونن
persianRex.number.test(value)
persianRex.text.test(value)

**Comment by ImanMh** [comment]
سلام، لطفا ورودی های خودتون رو هم بفرستید. احتمالا اینپوت متد شما رنج خاصی رو وارد می کنه.

**Comment by amirify** [comment]
مثلا: پلاک 5 یا هر عددی مثل 1973

**Comment by ImanMh** [comment]
خوب این اعداد که فارسی نیستند. شما پلاک ۵ رو امتحان کنید.
