### ISSUE TITLE
تشخیص اشتباه در متد hasRtl

### ISSUE THREAD

**Issue by amir-yaghoubi** [ImanMh/persianRex#13]
<p dir="rtl">سلام</p>
<p dir="rtl">متد <code>hasRtl</code> نوشته‌های انگلیسی همراه با space رو RTL تشخیص میده</p>
<pre><code class="language-javascript"> persianRex.hasRtl.test(&#39;this is not rtl&#39;) // return true
 persianRex.hasRtl.test(&#39;this-is-not-rtl&#39;) // return false</code></pre>

**Comment by ImanMh** [comment]
@amir-yaghoobi You are right about this, I will fix this one soon.

**Comment by amir-yaghoubi** [comment]
beside whitespaces, `,` will make `hasRtl` to return true.

so after removing `\\s` and `,` from regex, final regex looks like below:
```javascript
  persianRex.hasRtl = new RegExp(/(([۰-۹])|([کگۀی،تثجحخدغيًٌٍَپٰچژ‌ء-ةذ-عف-ٔ])|((،|؟|«|»|؛|٬)))/);
```
In tests i ran, this solved the issue for me

**Comment by ImanMh** [comment]
@amir-yaghoobi could you update the code, and also include new tests and send me a pull request so your name appears in contributors?

**Comment by amir-yaghoubi** [comment]
@ImanMh Sure, I will send a PR soon
