### ISSUE TITLE
Reducs name in NPM

### ISSUE THREAD

**Issue by mercmobily** [ImanMh/persianRex#15]
I apologise for opening an issue for an unrelated matter!

I wrote a module and would love to call it "reducs". At the moment, the "reducs" namespace is taken by you but there is no code (only package.json) and it's been like that for years.

Can I humbly ask you to please let us use the reducs namespace on NPM?

**Comment by ImanMh** [comment]
Sure, let me know your username and email that you used for npm and I will transfer the package ownership to you.

**Comment by mercmobily** [comment]
I will NEVER thank you enough. THANK YOU!

mercmobily is my handle, tonymobily@gmail.com is my email Thank you!

**Comment by ImanMh** [comment]
@mercmobily no problems bro, take it, it's yours. I added u as the maintainer and removed myself from the list. How ever I yet see the admin tab on the package page. I'm not sure but I think it takes some time to update that as well. If you don't have full control over the package let me know and I'll try something else.

**Comment by mercmobily** [comment]
Sorry again for polluting this fine project's issue list with my request. Thank you once again for your prompt response, thank you for the code you release, and thank you for being so awesome!

**Comment by mercmobily** [comment]
If you are curious...

https://www.npmjs.com/package/reducs

I would love to hear your thoughts :D

**Comment by ImanMh** [comment]
Yea man that's really cool, 30 lines of code! Well done 👏🏻
